from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

layout_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'', 'F2':'', 'keywords':'connector', 'match_pin_substring':False, 'datasheet':'~', 'F0':'J', 'F1':'Conn_01x03', 'description':'Generic connector, single row, 01x03, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'TerminalBlock_Altech_AK300-3_P5.00mm', 'pins':[
            Pin(num='1',name='VREL',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='5V',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_02x13_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'', 'F2':'', 'keywords':'connector', 'match_pin_substring':False, 'datasheet':'~', 'F0':'J', 'F1':'Conn_02x13_Odd_Even', 'description':'Generic connector, double row, 02x13, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_2x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_2x13_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='3V3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='10',name='UART1_RX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='11',name='UART2_RX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='12',name='PA07',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='13',name='UART2_TX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='14',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='15',name='UART2_CTS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='16',name='TWI1_SDA',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='17',name='3V3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='18',name='TWI1_SCK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='19',name='SPI1_MOSI',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='5V',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='20',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='21',name='SPI1_MISO',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='22',name='UART2_RTS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='23',name='SPI1_CLK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='24',name='SPI1_CS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='25',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='26',name='PA21',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='PA12',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='5V',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='PA11',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='GND',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='PA06',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='8',name='UART1_TX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='9',name='GND',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_01x04', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'', 'F2':'', 'keywords':'connector', 'match_pin_substring':False, 'datasheet':'~', 'F0':'J', 'F1':'Conn_01x04', 'description':'Generic connector, single row, 01x04, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='SDA',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='SCL',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='VCC',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='GND',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'ULN2003', 'dest':TEMPLATE, 'tool':SKIDL, '_aliases':Alias({'ULN2004', 'ULN2002A', 'ULN2004A', 'ULN2003A', 'ULN2002'}), 'F3':'', 'F2':'', 'keywords':'darlington transistor array', 'match_pin_substring':False, 'datasheet':'http://www.ti.com/lit/ds/symlink/uln2003a.pdf', 'F0':'U', 'F1':'ULN2003', 'description':'High Voltage, High Current Darlington Transistor Arrays, SOIC16/SOIC16W/DIP16/TSSOP16', 'ref_prefix':'U', 'num_units':1, 'fplist':['DIP*W7.62mm*', 'SOIC*3.9x9.9mm*P1.27mm*', 'SSOP*4.4x5.2mm*P0.65mm*', 'TSSOP*4.4x5mm*P0.65mm*', 'SOIC*W*5.3x10.2mm*P1.27mm*'], 'do_erc':True, 'aliases':Alias({'ULN2004', 'ULN2002A', 'ULN2004A', 'ULN2003A', 'ULN2002'}), 'pin':None, 'footprint':'Package_DIP:DIP-16_W7.62mm_Socket_LongPads', 'pins':[
            Pin(num='1',name='I1',func=Pin.types.INPUT,do_erc=True),
            Pin(num='10',name='O7',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='11',name='O6',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='12',name='O5',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='13',name='O4',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='14',name='O3',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='15',name='O2',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='16',name='O1',func=Pin.types.OPENCOLL,do_erc=True),
            Pin(num='2',name='I2',func=Pin.types.INPUT,do_erc=True),
            Pin(num='3',name='I3',func=Pin.types.INPUT,do_erc=True),
            Pin(num='4',name='I4',func=Pin.types.INPUT,do_erc=True),
            Pin(num='5',name='I5',func=Pin.types.INPUT,do_erc=True),
            Pin(num='6',name='I6',func=Pin.types.INPUT,do_erc=True),
            Pin(num='7',name='I7',func=Pin.types.INPUT,do_erc=True),
            Pin(num='8',name='GND',func=Pin.types.PWRIN,do_erc=True),
            Pin(num='9',name='COM',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_01x07', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'', 'F2':'', 'keywords':'connector', 'match_pin_substring':False, 'datasheet':'~', 'F0':'J', 'F1':'Conn_01x07', 'description':'Generic connector, single row, 01x07, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x07_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='DIN1',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='DIN2',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='DIN3',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='DIN4',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='DIN5',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='DIN6',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='DIN7',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'Conn_01x15', 'dest':TEMPLATE, 'tool':SKIDL, 'F3':'', 'F2':'', 'keywords':'connector', 'match_pin_substring':False, 'datasheet':'~', 'F0':'J', 'F1':'Conn_01x15', 'description':'Generic connector, single row, 01x15, script generated (kicad-library-utils/schlib/autogen/connector/)', 'ref_prefix':'J', 'num_units':1, 'fplist':['Connector*:*_1x??_*'], 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x15_P2.54mm_Vertical', 'pins':[
            Pin(num='1',name='PA12',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='10',name='SPI1_MOSI',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='11',name='SPI1_MISO',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='12',name='UART2_RTS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='13',name='SPI1_CLK',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='14',name='SPI1_CS',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='15',name='PA21',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='PA11',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='PA06',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='UART1_TX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='5',name='UART1_RX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='6',name='UART2_RX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='7',name='PA07',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='8',name='UART2_TX',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='9',name='UART2_CTS',func=Pin.types.PASSIVE,do_erc=True)] })])